-- Example promo seed data for Taree2y.
-- Review dates, limits, and event windows before running.

insert into public.promo_codes (
  code,
  discount_type,
  discount_value,
  max_discount,
  min_subtotal,
  first_booking_only,
  starts_at,
  ends_at,
  usage_limit,
  per_user_limit,
  is_active,
  route_from,
  route_to,
  eligible_tags,
  metadata
)
values
  (
    'AHLAN50',
    'flat',
    50,
    50,
    100,
    true,
    null,
    null,
    50000,
    1,
    true,
    null,
    null,
    array['first-time'],
    '{"title":"خصم أول استخدام","offer_banner":"خصم 50 ج.م لأول رحلة"}'::jsonb
  ),
  (
    'FIRSTTRIP70',
    'flat',
    70,
    70,
    150,
    true,
    null,
    null,
    10000,
    1,
    true,
    null,
    null,
    array['first-time'],
    '{"title":"أول رحلة أقوى","offer_banner":"70 ج.م على أول عملية شراء"}'::jsonb
  ),
  (
    'EID26',
    'percent',
    20,
    120,
    150,
    false,
    '2026-03-15T00:00:00+02:00',
    '2026-04-20T23:59:59+02:00',
    250000,
    1,
    true,
    null,
    null,
    array['eid','seasonal'],
    '{"title":"عيدية طريقي","offer_banner":"خصم 20% بمناسبة العيد"}'::jsonb
  ),
  (
    'SUMMER26',
    'percent',
    15,
    150,
    200,
    false,
    '2026-06-01T00:00:00+03:00',
    '2026-09-15T23:59:59+03:00',
    250000,
    2,
    true,
    null,
    null,
    array['summer','beach'],
    '{"destinations":["مرسى مطروح","الغردقة","شرم الشيخ","دهب"],"title":"فورمة الصيف","offer_banner":"خصم 15% على رحلات الصيف"}'::jsonb
  ),
  (
    'SA3EED15',
    'percent',
    15,
    120,
    150,
    false,
    null,
    null,
    100000,
    2,
    true,
    null,
    null,
    array['upper-egypt'],
    '{"destinations":["سوهاج","قنا","الأقصر","أسوان"],"title":"أهالي الصعيد","offer_banner":"خصم 15% على رحلات الصعيد"}'::jsonb
  ),
  (
    'STUDENT20',
    'percent',
    20,
    80,
    120,
    false,
    null,
    null,
    100000,
    1,
    true,
    null,
    null,
    array['student'],
    '{"requires_student_profile":true,"title":"خصم الطلبة","offer_banner":"خصم 20% للطلبة"}'::jsonb
  )
on conflict (code) do update
set
  discount_type = excluded.discount_type,
  discount_value = excluded.discount_value,
  max_discount = excluded.max_discount,
  min_subtotal = excluded.min_subtotal,
  first_booking_only = excluded.first_booking_only,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  usage_limit = excluded.usage_limit,
  per_user_limit = excluded.per_user_limit,
  is_active = excluded.is_active,
  route_from = excluded.route_from,
  route_to = excluded.route_to,
  eligible_tags = excluded.eligible_tags,
  metadata = excluded.metadata;
