// Auto-generated by taree2y_refactor_patch.sh
const CITIES = ["القاهرة", "الإسكندرية", "مرسى مطروح", "بورسعيد", "الإسماعيلية", "السويس", "دمياط", "شرم الشيخ", "الغردقة", "دهب", "طابا", "المنصورة", "سوهاج", "قنا", "الأقصر", "أسوان"];

const DIRECT_ROUTES = {
  'القاهرة-الإسكندرية': 150, 'الإسكندرية-القاهرة': 150, 'القاهرة-المنصورة': 120, 'المنصورة-القاهرة': 120,
  'القاهرة-بورسعيد': 140, 'بورسعيد-القاهرة': 140, 'القاهرة-الإسماعيلية': 100, 'الإسماعيلية-القاهرة': 100,
  'القاهرة-السويس': 110, 'السويس-القاهرة': 110, 'القاهرة-دمياط': 160, 'دمياط-القاهرة': 160,
  'القاهرة-مرسى مطروح': 300, 'مرسى مطروح-القاهرة': 300, 'الإسكندرية-مرسى مطروح': 180, 'مرسى مطروح-الإسكندرية': 180,
  'القاهرة-الغردقة': 350, 'الغردقة-القاهرة': 350, 'القاهرة-شرم الشيخ': 400, 'شرم الشيخ-القاهرة': 400,
  'القاهرة-دهب': 450, 'دهب-القاهرة': 450, 'القاهرة-سوهاج': 320, 'سوهاج-القاهرة': 320,
  'القاهرة-قنا': 400, 'قنا-القاهرة': 400, 'القاهرة-الأقصر': 500, 'الأقصر-القاهرة': 500,
  'القاهرة-أسوان': 600, 'أسوان-القاهرة': 600, 'الأقصر-أسوان': 150, 'أسوان-الأقصر': 150,
};

const COMPANY_FEES = { 'جو باص': 0.20, 'سوبر جيت': 0.15, 'بلو باص': 0.25 };

const DRIVERS = [
  { name: 'أسطى محمود سعيد', rating: 4.8, trips: 342, img: '👨🏽‍✈️' },
  { name: 'كابتن أحمد علي', rating: 4.6, trips: 156, img: '👨🏻‍✈️' },
  { name: 'كابتن سيد رمضان', rating: 4.9, trips: 520, img: '👨🏾‍✈️' }
];

const getLocalDateInputValue = () => {
  const now = new Date();
  const offset = now.getTimezoneOffset();
  return new Date(now.getTime() - offset * 60000).toISOString().split('T')[0];
};

const hashString = (str) => {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h += (h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24);
  }
  return Math.abs(h >>> 0);
};

const createSeededRandom = (seed) => {
  let state = seed % 2147483647;
  if (state <= 0) state += 2147483646;
  return () => {
    state = (state * 16807) % 2147483647;
    return (state - 1) / 2147483646;
  };
};

const clamp = (value, min, max) => Math.min(max, Math.max(min, value));

const addMinutesToTime = (timeStr, minutesToAdd) => {
  const [h, m] = timeStr.split(':').map(Number);
  const total = h * 60 + m + minutesToAdd;
  const normalized = ((total % 1440) + 1440) % 1440;
  const hh = Math.floor(normalized / 60);
  const mm = normalized % 60;
  return `${String(hh).padStart(2, '0')}:${String(mm).padStart(2, '0')}`;
};

const getDateAtLocalMidnight = (dateStr) => new Date(`${dateStr}T00:00:00`);

const getDaysUntilTrip = (tripDate) => {
  const today = getDateAtLocalMidnight(getLocalDateInputValue());
  const tripDay = getDateAtLocalMidnight(tripDate);
  return Math.round((tripDay - today) / (1000 * 60 * 60 * 24));
};

const ROUTE_META = {
  'القاهرة-الإسكندرية': { durationMin: 180, popularity: 0.95, hasRestStop: false },
  'الإسكندرية-القاهرة': { durationMin: 180, popularity: 0.95, hasRestStop: false },
  'القاهرة-المنصورة': { durationMin: 150, popularity: 0.78, hasRestStop: false },
  'المنصورة-القاهرة': { durationMin: 150, popularity: 0.78, hasRestStop: false },
  'القاهرة-بورسعيد': { durationMin: 210, popularity: 0.72, hasRestStop: false },
  'بورسعيد-القاهرة': { durationMin: 210, popularity: 0.72, hasRestStop: false },
  'القاهرة-الإسماعيلية': { durationMin: 120, popularity: 0.70, hasRestStop: false },
  'الإسماعيلية-القاهرة': { durationMin: 120, popularity: 0.70, hasRestStop: false },
  'القاهرة-السويس': { durationMin: 135, popularity: 0.68, hasRestStop: false },
  'السويس-القاهرة': { durationMin: 135, popularity: 0.68, hasRestStop: false },
  'القاهرة-دمياط': { durationMin: 210, popularity: 0.60, hasRestStop: false },
  'دمياط-القاهرة': { durationMin: 210, popularity: 0.60, hasRestStop: false },
  'القاهرة-مرسى مطروح': { durationMin: 360, popularity: 0.75, hasRestStop: true },
  'مرسى مطروح-القاهرة': { durationMin: 360, popularity: 0.75, hasRestStop: true },
  'الإسكندرية-مرسى مطروح': { durationMin: 240, popularity: 0.70, hasRestStop: false },
  'مرسى مطروح-الإسكندرية': { durationMin: 240, popularity: 0.70, hasRestStop: false },
  'القاهرة-الغردقة': { durationMin: 390, popularity: 0.76, hasRestStop: true },
  'الغردقة-القاهرة': { durationMin: 390, popularity: 0.76, hasRestStop: true },
  'القاهرة-شرم الشيخ': { durationMin: 480, popularity: 0.82, hasRestStop: true },
  'شرم الشيخ-القاهرة': { durationMin: 480, popularity: 0.82, hasRestStop: true },
  'القاهرة-دهب': { durationMin: 540, popularity: 0.74, hasRestStop: true },
  'دهب-القاهرة': { durationMin: 540, popularity: 0.74, hasRestStop: true },
  'القاهرة-سوهاج': { durationMin: 480, popularity: 0.72, hasRestStop: true },
  'سوهاج-القاهرة': { durationMin: 480, popularity: 0.72, hasRestStop: true },
  'القاهرة-قنا': { durationMin: 570, popularity: 0.70, hasRestStop: true },
  'قنا-القاهرة': { durationMin: 570, popularity: 0.70, hasRestStop: true },
  'القاهرة-الأقصر': { durationMin: 660, popularity: 0.82, hasRestStop: true },
  'الأقصر-القاهرة': { durationMin: 660, popularity: 0.82, hasRestStop: true },
  'القاهرة-أسوان': { durationMin: 840, popularity: 0.78, hasRestStop: true },
  'أسوان-القاهرة': { durationMin: 840, popularity: 0.78, hasRestStop: true },
  'الأقصر-أسوان': { durationMin: 210, popularity: 0.65, hasRestStop: false },
  'أسوان-الأقصر': { durationMin: 210, popularity: 0.65, hasRestStop: false },
};

const SHORT_ROUTE_TEMPLATES = [
  { departureTime: '06:00', company: 'جو باص', class: 'اقتصادي مميز' },
  { departureTime: '08:00', company: 'سوبر جيت', class: 'اقتصادي مميز' },
  { departureTime: '10:00', company: 'بلو باص', class: 'اقتصادي مميز' },
  { departureTime: '12:30', company: 'جو باص', class: 'VIP رجال أعمال' },
  { departureTime: '15:00', company: 'سوبر جيت', class: 'اقتصادي مميز' },
  { departureTime: '18:00', company: 'بلو باص', class: 'اقتصادي مميز' },
  { departureTime: '21:00', company: 'جو باص', class: 'VIP رجال أعمال' },
];

const MEDIUM_ROUTE_TEMPLATES = [
  { departureTime: '06:00', company: 'جو باص', class: 'اقتصادي مميز' },
  { departureTime: '08:30', company: 'سوبر جيت', class: 'VIP رجال أعمال' },
  { departureTime: '11:00', company: 'بلو باص', class: 'اقتصادي مميز' },
  { departureTime: '14:00', company: 'جو باص', class: 'VIP رجال أعمال' },
  { departureTime: '17:30', company: 'سوبر جيت', class: 'اقتصادي مميز' },
  { departureTime: '21:00', company: 'بلو باص', class: 'اقتصادي مميز' },
];

const LONG_ROUTE_TEMPLATES = [
  { departureTime: '07:00', company: 'جو باص', class: 'اقتصادي مميز' },
  { departureTime: '10:00', company: 'سوبر جيت', class: 'VIP رجال أعمال' },
  { departureTime: '19:30', company: 'جو باص', class: 'اقتصادي مميز' },
  { departureTime: '22:00', company: 'سوبر جيت', class: 'VIP رجال أعمال' },
];

const getScheduleTemplatesForRoute = (routeKey) => {
  const meta = ROUTE_META[routeKey];
  if (!meta) return MEDIUM_ROUTE_TEMPLATES;
  if (meta.durationMin <= 210) return SHORT_ROUTE_TEMPLATES;
  if (meta.durationMin >= 480) return LONG_ROUTE_TEMPLATES;
  return MEDIUM_ROUTE_TEMPLATES;
};

const getTripDepartureDateTime = (trip) => new Date(`${trip.date}T${trip.departureTime}:00`);

const getTripArrivalDateTime = (trip) => {
  const departure = getTripDepartureDateTime(trip);
  const arrival = new Date(`${trip.date}T${trip.arrivalTime}:00`);
  if (arrival < departure) arrival.setDate(arrival.getDate() + 1);
  return arrival;
};

const getTripLifecycleStatus = (trip, now = new Date()) => {
  const departure = getTripDepartureDateTime(trip);
  const arrival = getTripArrivalDateTime(trip);
  const totalMs = Math.max(1, arrival - departure);
  const elapsedPct = clamp(((now - departure) / totalMs) * 100, 0, 100);
  const routeMeta = ROUTE_META[`${trip.from}-${trip.to}`] || { hasRestStop: trip.durationHour >= 4.5 };

  if (now < new Date(departure.getTime() - 30 * 60 * 1000)) {
    return { key: 'scheduled', progress: 0, statusText: 'لسه متحركتش (في الانتظار)' };
  }

  if (now < departure) {
    return { key: 'boarding', progress: 0, statusText: 'بدأ تجهيز الرحلة والصعود' };
  }

  if (now >= arrival) {
    return { key: 'arrived', progress: 100, statusText: 'وصلت بالسلامة حمدالله على السلامة!' };
  }

  if (routeMeta.hasRestStop && elapsedPct >= 45 && elapsedPct <= 60) {
    return { key: 'rest_stop', progress: elapsedPct, statusText: 'الرحلة في استراحة قصيرة' };
  }

  if (elapsedPct >= 85) {
    return { key: 'final_approach', progress: elapsedPct, statusText: 'الرحلة قربت توصل' };
  }

  return { key: 'en_route', progress: elapsedPct, statusText: 'الرحلة شغالة حسب الجدول' };
};

const getCancellationPolicy = (trip, now = new Date()) => {
  const departure = getTripDepartureDateTime(trip);
  const hoursToDeparture = (departure - now) / (1000 * 60 * 60);
  const baseFee = COMPANY_FEES[trip.company] || 0.20;

  if (trip.status !== 'upcoming') {
    return {
      allowed: false,
      feeRatio: 1,
      refundAmount: 0,
      message: 'الرحلة دي غير قابلة للإلغاء الآن',
      label: 'غير قابل للإلغاء',
    };
  }

  if (hoursToDeparture <= 2) {
    return {
      allowed: false,
      feeRatio: 1,
      refundAmount: 0,
      message: 'فات وقت الإلغاء المسموح (أقل من ساعتين على التحرك)',
      label: 'فات وقت الإلغاء',
    };
  }

  let feeRatio = baseFee;
  let label = 'رسوم الإلغاء الأساسية';

  if (hoursToDeparture > 24) {
    feeRatio = Math.max(0.10, baseFee - 0.05);
    label = 'إلغاء مبكر';
  } else if (hoursToDeparture <= 6) {
    feeRatio = clamp(baseFee + 0.15, baseFee, 0.75);
    label = 'إلغاء متأخر';
  }

  const refundAmount = Math.max(0, Math.round((trip.finalTotal || 0) * (1 - feeRatio)));

  return {
    allowed: true,
    feeRatio,
    refundAmount,
    message: label,
    label,
    hoursToDeparture,
  };
};

const MIN_BOOKING_LEAD_MINUTES = 120;

const getTripMinutesUntilDeparture = (trip, now = new Date()) => {
  return Math.floor((getTripDepartureDateTime(trip) - now) / 60000);
};

const getTripBookability = (trip, now = new Date()) => {
  const departure = getTripDepartureDateTime(trip);
  const arrival = getTripArrivalDateTime(trip);
  const minutesUntilDeparture = getTripMinutesUntilDeparture(trip, now);

  if (trip.status && ['cancelled', 'refund_pending'].includes(trip.status)) {
    return {
      canBook: false,
      code: 'inactive',
      reason: 'الحجز مقفول على الرحلة دي حالياً',
      minutesUntilDeparture,
    };
  }

  if (now >= arrival) {
    return {
      canBook: false,
      code: 'finished',
      reason: 'الرحلة دي خلصت بالفعل',
      minutesUntilDeparture,
    };
  }

  if (now >= departure) {
    return {
      canBook: false,
      code: 'departed',
      reason: 'الرحلة دي اتحركت بالفعل',
      minutesUntilDeparture,
    };
  }

  if (minutesUntilDeparture < MIN_BOOKING_LEAD_MINUTES) {
    return {
      canBook: false,
      code: 'cutoff',
      reason: 'الحجز بيقفل قبل التحرك بساعتين على الأقل',
      minutesUntilDeparture,
    };
  }

  return {
    canBook: true,
    code: 'bookable',
    reason: 'متاح للحجز',
    minutesUntilDeparture,
  };
};


const getAvailableSeatsCount = (trip) => {
  if (Number.isFinite(Number(trip?.availableSeatsCount))) {
    return Math.max(0, Number(trip.availableSeatsCount));
  }

  return Array.isArray(trip?.seats)
    ? trip.seats.filter((seat) => seat?.status === 'available').length
    : 0;
};

const getTripSearchUiState = (trip, now = new Date()) => {
  const availableSeats = getAvailableSeatsCount(trip);
  const bookability = getTripBookability(
    {
      ...trip,
      status: trip?.status || 'upcoming',
    },
    now,
  );

  const isSoldOut = availableSeats <= 0;
  const isActionable = bookability.canBook && !isSoldOut;

  return {
    availableSeats,
    bookability,
    isSoldOut,
    isActionable,
    isClosedBySchedule: ['finished', 'departed', 'cutoff'].includes(bookability.code),
    unavailabilityReason: isSoldOut ? 'ممتلئة حالياً' : bookability.reason,
  };
};

const getSearchAvailabilityNotice = (trips = [], now = new Date()) => {
  const safeTrips = Array.isArray(trips) ? trips : [];
  if (!safeTrips.length) return null;

  const metrics = safeTrips.map((trip) => ({
    trip,
    searchUi: getTripSearchUiState(trip, now),
  }));

  const activeTrips = metrics.filter((item) => item.searchUi.isActionable);
  const closedTrips = metrics.filter((item) => !item.searchUi.isActionable);
  const totalAvailableSeats = activeTrips.reduce(
    (sum, item) => sum + item.searchUi.availableSeats,
    0,
  );

  if (!activeTrips.length) {
    return {
      tone: 'warning',
      title: 'النتائج دي مقفولة حالياً',
      text: 'كل الرحلات الظاهرة فات وقت الحجز عليها أو انتهت بالفعل، لكن تقدر تراجع بياناتها لو محتاج.',
    };
  }

  if (totalAvailableSeats <= 10) {
    return {
      tone: 'warning',
      title: 'الإتاحة قليلة على النتائج دي',
      text: 'لو الرحلة مناسبة، احجز بسرعة قبل ما المقاعد المتاحة تقل أكتر.',
    };
  }

  if (totalAvailableSeats <= 30 || closedTrips.length >= activeTrips.length) {
    return {
      tone: 'info',
      title: 'فيه اختيارات كويسة',
      text: 'قارن الوقت والمحطة والسعر براحتك، لكن بعض الرحلات بدأت تتملي أو خرجت من وقت الحجز.',
    };
  }

  return {
    tone: 'success',
    title: 'الإتاحة مريحة حاليًا',
    text: `لسه فيه ${totalAvailableSeats} مقعد متاح على رحلات ما زالت صالحة للحجز في اليوم ده.`,
  };
};

const generateSeats = (tripId, tripDate, tripTime, routeKey, company, seatClass) => {
  const seed = hashString(`${tripId}-${tripDate}-${tripTime}`);
  const rand = createSeededRandom(seed);
  const daysUntilTrip = getDaysUntilTrip(tripDate);
  const meta = ROUTE_META[routeKey] || { popularity: 0.65 };

  let fillRatio;
  if (daysUntilTrip <= 0) fillRatio = 0.86;
  else if (daysUntilTrip <= 1) fillRatio = 0.74;
  else if (daysUntilTrip <= 3) fillRatio = 0.60;
  else if (daysUntilTrip <= 7) fillRatio = 0.47;
  else if (daysUntilTrip <= 14) fillRatio = 0.34;
  else fillRatio = 0.22;

  fillRatio += (meta.popularity - 0.5) * 0.25;
  if (seatClass.includes('VIP')) fillRatio += 0.05;
  if (company === 'سوبر جيت') fillRatio += 0.03;
  fillRatio = clamp(fillRatio, 0.10, 0.95);

  const seats = [];
  for (let idx = 0; idx < 40; idx++) {
    const row = Math.floor(idx / 4) + 1;
    const col = ['A', 'B', 'C', 'D'][idx % 4];
    const frontBias = row <= 3 ? 0.06 : row >= 9 ? -0.03 : 0;
    const isBooked = rand() < clamp(fillRatio + frontBias, 0.05, 0.98);

    seats.push({
      id: idx + 1,
      number: `${row}${col}`,
      status: isBooked ? 'booked' : 'available',
    });
  }

  return seats;
};

const generateTrips = (from, to, date) => {
  if (!from || !to || from === to) return { trips: [], isDirect: false };

  const routeKey = `${from}-${to}`;
  const basePrice = DIRECT_ROUTES[routeKey];
  if (!basePrice) return { trips: [], isDirect: false };

  const routeMeta = ROUTE_META[routeKey] || {
    durationMin: Math.max(120, Math.round(basePrice * 1.3)),
    popularity: 0.65,
    hasRestStop: basePrice >= 300,
  };

  const routeSeed = hashString(`${routeKey}-${date}`);
  const rand = createSeededRandom(routeSeed);
  const daysUntilTrip = getDaysUntilTrip(date);
  const scheduleTemplates = getScheduleTemplatesForRoute(routeKey);

  const trips = scheduleTemplates.map((schedule, i) => {
    const isVIP = schedule.class.includes('VIP');
    const companyMultiplier = schedule.company === 'بلو باص' ? 1.04 : schedule.company === 'سوبر جيت' ? 1.08 : 1.0;
    const classMultiplier = isVIP ? 1.42 : 1.0;
    const hour = Number(schedule.departureTime.split(':')[0]);
    const timeMultiplier = hour >= 19 || hour < 6 ? 1.06 : hour >= 7 && hour <= 9 ? 1.03 : 1.0;
    const bookingWindowMultiplier = daysUntilTrip <= 1 ? 1.10 : daysUntilTrip <= 3 ? 1.05 : daysUntilTrip >= 14 ? 0.98 : 1.0;
    const variabilityMultiplier = 0.97 + rand() * 0.07;

    const rawPrice = basePrice * companyMultiplier * classMultiplier * timeMultiplier * bookingWindowMultiplier * variabilityMultiplier;
    const price = Math.max(basePrice, Math.round(rawPrice / 10) * 10);

    const operatorDurationDelta = schedule.company === 'سوبر جيت' ? -12 : schedule.company === 'بلو باص' ? 8 : 0;
    const variance = Math.round(rand() * 24 - 12);
    const durationMin = Math.max(90, routeMeta.durationMin + operatorDurationDelta + variance);

    const routeCode = hashString(routeKey).toString(36).toUpperCase().slice(0, 4);
    const tripId = `TRP-${routeCode}-${date.replaceAll('-', '')}-${i + 1}`;

    return {
      id: tripId,
      from,
      to,
      date,
      departureTime: schedule.departureTime,
      arrivalTime: addMinutesToTime(schedule.departureTime, durationMin),
      durationHour: Number((durationMin / 60).toFixed(1)),
      price,
      company: schedule.company,
      class: schedule.class,
      rating: (4.1 + rand() * 0.8).toFixed(1),
      seats: generateSeats(tripId, date, schedule.departureTime, routeKey, schedule.company, schedule.class),
      driver: DRIVERS[i % DRIVERS.length],
      hasRestStop: routeMeta.hasRestStop,
    };
  });

  const cheapest = [...trips].sort((a, b) => a.price - b.price)[0];
  const fastest = [...trips].sort((a, b) => a.durationHour - b.durationHour)[0];

  return {
    trips: trips.map((t) => ({
      ...t,
      badge:
        t.id === cheapest?.id
          ? 'cheapest'
          : t.id === fastest?.id
          ? 'fastest'
          : t.class.includes('VIP')
          ? 'vip'
          : null,
    })),
    isDirect: true,
  };
};

const getFallbackTripBookability = (rawStatus = '') => {
  if (['cancelled', 'refund_pending'].includes(rawStatus)) {
    return {
      canBook: false,
      code: 'inactive',
      reason: 'الحجز مقفول على الرحلة دي حالياً',
      minutesUntilDeparture: null,
    };
  }

  if (rawStatus === 'past') {
    return {
      canBook: false,
      code: 'finished',
      reason: 'الرحلة دي خلصت بالفعل',
      minutesUntilDeparture: null,
    };
  }

  return {
    canBook: true,
    code: 'bookable',
    reason: 'متاح للحجز',
    minutesUntilDeparture: null,
  };
};

const getTripBookingUiState = (trip, now = new Date()) => {
  const rawStatus = String(trip?.status || '').trim();
  const hasSchedule = Boolean(
    trip?.date && trip?.departureTime && trip?.arrivalTime,
  );

  const lifecycle = hasSchedule ? getTripLifecycleStatus(trip, now) : null;
  const bookability = hasSchedule
    ? getTripBookability(trip, now)
    : getFallbackTripBookability(rawStatus);

  let displayStatus = 'upcoming';

  if (rawStatus === 'cancelled') {
    displayStatus = 'cancelled';
  } else if (rawStatus === 'refund_pending') {
    displayStatus = 'refund_pending';
  } else if (rawStatus === 'past') {
    displayStatus = 'past';
  } else if (['finished', 'departed'].includes(bookability?.code)) {
    displayStatus = 'past';
  }

  return {
    rawStatus,
    displayStatus,
    lifecycle,
    bookability,
    pastCode:
      ['finished', 'departed'].includes(bookability?.code)
        ? bookability.code
        : rawStatus === 'past'
        ? 'finished'
        : null,
    isUpcoming: displayStatus === 'upcoming',
    isRefundPending: displayStatus === 'refund_pending',
    isCancelled: displayStatus === 'cancelled',
    isPast: displayStatus === 'past',
    isAvailable: displayStatus === 'upcoming',
  };
};

const getAvailableSeatsCount = (trip) => {
  if (Number.isFinite(Number(trip?.availableSeatsCount))) {
    return Math.max(0, Number(trip.availableSeatsCount));
  }

  return Array.isArray(trip?.seats)
    ? trip.seats.filter((seat) => seat?.status === 'available').length
    : 0;
};

const getSearchAvailabilityNotice = (trips = []) => {
  const safeTrips = Array.isArray(trips) ? trips : [];
  if (!safeTrips.length) return null;

  const metrics = safeTrips.map((trip) => ({
    trip,
    availableSeats: getAvailableSeatsCount(trip),
  }));

  const totalTrips = metrics.length;
  const soldOutTripsCount = metrics.filter((item) => item.availableSeats === 0).length;
  const activeTripsCount = totalTrips - soldOutTripsCount;
  const lowAvailabilityTripsCount = metrics.filter(
    (item) => item.availableSeats > 0 && item.availableSeats <= 8,
  ).length;
  const totalAvailableSeats = metrics.reduce(
    (sum, item) => sum + item.availableSeats,
    0,
  );

  if (activeTripsCount === 0) {
    return {
      tone: 'warning',
      title: 'الإتاحة شبه منتهية',
      text: 'النتائج دي حالياً ممتلئة أو مفيهاش مقاعد صالحة للحجز.',
    };
  }

  if (
    totalAvailableSeats <= 12 ||
    lowAvailabilityTripsCount >= Math.ceil(activeTripsCount / 2)
  ) {
    return {
      tone: 'warning',
      title: 'الإتاحة بتخلص بسرعة',
      text: `${lowAvailabilityTripsCount || activeTripsCount} من ${activeTripsCount} رحلات فيها مقاعد محدودة حالياً، فلو لقيت المناسب احجز بسرعة.`,
    };
  }

  if (totalAvailableSeats <= activeTripsCount * 7) {
    return {
      tone: 'info',
      title: 'فيه اختيارات كويسة',
      text: `لسه فيه ${totalAvailableSeats} مقعد متاح عبر ${activeTripsCount} رحلات، لكن بعض الرحلات بدأت تتملي.`,
    };
  }

  return {
    tone: 'success',
    title: 'الإتاحة مريحة حاليًا',
    text: `لسه فيه ${totalAvailableSeats} مقعد متاح عبر ${activeTripsCount} رحلات مرتبطة بالسيرفر، فممكن تقارن براحتك.`,
  };
};


export {
  CITIES,
  DIRECT_ROUTES,
  ROUTE_META,
  getLocalDateInputValue,
  getTripLifecycleStatus,
  getCancellationPolicy,
  getTripBookability,
  getTripBookingUiState,
  getAvailableSeatsCount,
  getSearchAvailabilityNotice,
  generateTrips,
  getTripSearchUiState,
};
